image: node:15.12-alpine3.13

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  only:
    - master
