image: node:16.17.1

stages:
  - test
  - deploy
  - scrape

test:
  stage: test
  script:
    - npm install
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master

scrape:
  stage: scrape
  image: docker:latest
  services:
    - docker:dind
  script:
    - mv scraper-config.json .
    - apk add jq
    - docker run -i --env API_KEY=$API_KEY --env APPLICATION_ID=$APPLICATION_ID
      -e "CONFIG=$(cat scraper-config.json | jq -r tostring)"
      algolia/docsearch-scraper
  only:
    - master
