image: node:16.17.1

stages:
  - test
  - deploy
  - scrape

test:
  stage: test
  script:
    - npm install
    - npm run build
  rules:
    - if: '$SCHEDULER_TAG == "scrape"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master" && $SCHEDULER_TAG != "scrape"'
      when: on_success

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  rules:
    - if: '$SCHEDULER_TAG == "scrape"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master" && $SCHEDULER_TAG != "scrape"'
      when: on_success

scrape:
  stage: scrape
  image: docker:latest
  script:
    - apk add jq
    - docker run -i -e API_KEY=$API_KEY APPLICATION_ID=$APPLICATION_ID  "CONFIG=$(cat scraper-config.json | jq -r tostring)" algolia/docsearch-scraper
  rules:
    - if: '$SCHEDULER_TAG == "scrape"'
      when: on_success