image: node:16.17.1

stages:
  - test
  - deploy
  - scrape

test:
  stage: test
  script:
    - npm install
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master
  rules:
    - if: '$SCHEDULER_TAG == "scrape"' # variable is set in scheduled job
      when: never

scrape:
  stage: scrape
  image: docker:latest
  script:
    - apk add jq
    - docker run -i -e API_KEY=$API_KEY APPLICATION_ID=$APPLICATION_ID  "CONFIG=$(cat config.json | jq -r tostring)" algolia/docsearch-scraper
  only:
    - master
  rules:
    - if: '$SCHEDULER_TAG == "scrape"' # variable is set in scheduled job
      when: on_success