image: node:16.17.1

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master
